version: "3"

services:
  gunicorn:
    container_name: gunicorn
    build:
      dockerfile: Gunicorn.Dockerfile

  nginx:
    build:
      dockerfile: Nginx.Dockerfile
    # ports:
    #   - 8080:80
    networks:
      - default
      - nginx
    depends_on:
      - gunicorn

networks:
  default:
  nginx:
    external: true
