version: "3"

services:
  gunicorn:
    container_name: gunicorn
    build:
      dockerfile: Gunicorn.Dockerfile
      no_cache: true

  nginx:
    build:
      dockerfile: Nginx.Dockerfile
      no_cache: true
    networks:
      - default
      - nginx

networks:
  default:
  nginx:
    external: true
