version: "3"

services:
  gunicorn:
    build:
      dockerfile: Gunicorn.Dockerfile

  nginx:
    build:
      dockerfile: Nginx.Dockerfile
    ports:
      - 80:80
    networks:
      - nginx

networks:
  nginx:
    external: true
